'use client';
import Link from 'next/link';
import { motion } from 'framer-motion';
import { useState } from 'react';
import { createClient } from '@/lib/supabase/client';

type Character={name:string;power:number;speed:number;focus:number;rank:string};
export default function StolenSuppliesClient({userId,initialCharacter}:{userId:string;initialCharacter:Character}){
 const db=createClient(); const [c,setC]=useState(initialCharacter); const [phase,setPhase]=useState<'brief'|'pursuit'|'complete'>('brief'); const [distance,setDistance]=useState(100); const [chakra,setChakra]=useState(100); const [text,setText]=useState('A thief vanished into the eastern ravine with village supplies.'); const [locked,setLocked]=useState(false); const [flash,setFlash]=useState(false);
 const flashStepLearned=c.rank.toLowerCase().includes('flash');
 function start(){setDistance(100);setChakra(100);setPhase('pursuit');setText('Target spotted. Close the distance before the ravine exit.')}
 function move(amount:number,label:string,cost=0){if(locked||distance<=0||chakra<cost)return;setLocked(true);if(cost)setChakra(v=>Math.max(0,v-cost));const next=Math.max(0,distance-amount);setDistance(next);setText(`${label} · ${amount}m gained`);if(label==='FLASH STEP'){setFlash(true);setTimeout(()=>setFlash(false),350)}if(next===0){void finish();return}setTimeout(()=>setLocked(false),label==='FLASH STEP'?380:620)}
 async function finish(){setLocked(true);setText('SUPPLIES RECOVERED · Kairo watches your final burst of speed.');const {data}=await db.from('characters').update({rank:'Chakra Adept · Flash Step',power:c.power+12,speed:c.speed+3,focus:c.focus+1,updated_at:new Date().toISOString()}).eq('user_id',userId).select('name,power,speed,focus,rank').single();if(data)setC(data as Character);setTimeout(()=>setPhase('complete'),900)}
 return <main className={`ravine-shell ${flash?'flash-active':''}`}><div className="ravine-sky"/><div className="ravine-cliffs"/><header><span>D-RANK // STOLEN SUPPLIES</span><strong>{text}</strong></header>{phase==='brief'&&<section className="brief-card"><span>MISSION 002</span><h1>Catch the thief.</h1><p>The path is narrow and the target is faster than you. Kairo's lesson returns to you: move without wasting chakra.</p><button onClick={start}>BEGIN PURSUIT</button><Link href="/village">RETURN TO VILLAGE</Link></section>}{phase==='pursuit'&&<><div className="pursuit-hud"><div><span>DISTANCE</span><strong>{distance}m</strong><i><em style={{width:`${100-distance}%`}}/></i></div><div><span>CHAKRA</span><strong>{chakra}/100</strong><i><em style={{width:`${chakra}%`}}/></i></div></div><motion.div className="runner player-runner" animate={flash?{x:[0,130,115]}:{y:[0,-5,0]}}><div/><span/></motion.div><motion.div className="runner thief-runner" animate={{y:[0,-4,0]}} transition={{repeat:Infinity,duration:.5}}><div/><span/><b>SUPPLIES</b></motion.div><nav><button disabled={locked} onClick={()=>move(12,'SPRINT')}>SPRINT</button><button disabled={locked||chakra<15} onClick={()=>move(18,'CHAKRA DASH',15)}>CHAKRA DASH · 15</button><button className="flash-step" disabled={locked||chakra<30} onClick={()=>move(35,'FLASH STEP',30)}>FLASH STEP · 30</button></nav></>}{phase==='complete'&&<section className="complete-card"><span>TECHNIQUE ACQUIRED</span><h1>FLASH STEP</h1><p>Explosive chakra-assisted movement. Your first true mobility technique is now part of your style.</p><div>+12 POWER · +3 SPEED · +1 FOCUS</div><Link href="/village">RETURN TO KAIRO</Link></section>} {flashStepLearned&&phase==='brief'&&<div className="learned-stamp">FLASH STEP MASTERED</div>}</main>
}
