'use client';
import {AnimatePresence,motion} from 'framer-motion';
import {useMemo,useState} from 'react';
import {createClient} from '@/lib/supabase/client';
type C={id:string;name:string;power:number;strength:number;speed:number;endurance:number;focus:number;stamina:number;rank:string;world:string};
const hair=['Obsidian','Crimson','Silver','Midnight Blue'],eyes=['Slate','Amber','Emerald','Violet'],outfits=['Rookie Black','Ash Wrap','Field Grey','Night Scout'];
export default function GameClient({userId,initialCharacter}:{userId:string;initialCharacter:C|null}){
 const db=createClient(),[screen,setScreen]=useState(initialCharacter?'world':'boot'),[name,setName]=useState(initialCharacter?.name??'Ari'),[h,setH]=useState(hair[0]),[e,setE]=useState(eyes[0]),[o,setO]=useState(outfits[0]),[c,setC]=useState<C|null>(initialCharacter),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false);const n=useMemo(()=>name.trim()||'Ari',[name]);
 async function enter(){setBusy(true);const {data}=await db.from('characters').insert({user_id:userId,name:n}).select('id,name,power,strength,speed,endurance,focus,stamina,rank,world').single();if(data){setC(data as C);setScreen('world')}setBusy(false)}
 async function train(){if(!c||busy)return;setBusy(true);const {data}=await db.from('characters').update({power:c.power+1,updated_at:new Date().toISOString()}).eq('user_id',userId).select('id,name,power,strength,speed,endurance,focus,stamina,rank,world').single();if(data){setC(data as C);setSaved(true);setTimeout(()=>setSaved(false),900)}setBusy(false)}
 async function signOut(){await db.auth.signOut();location.href='/login'}
 return <main className="game-shell"><div className="noise"/><div className="vignette"/><button className="account-button" onClick={signOut}>SIGN OUT</button><AnimatePresence mode="wait">
 {screen==='boot'&&<motion.section key="boot" className="screen boot-screen" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.div className="orb" initial={{scale:.1}} animate={{scale:1}}/><p className="eyebrow">EVERY LEGEND STARTS WITH NOTHING.</p><h1>ANIME ASCENSION</h1><p className="tagline">YOURS STARTS NOW.</p><button className="primary" onClick={()=>setScreen('creator')}>BEGIN</button></motion.section>}
 {screen==='creator'&&<motion.section key="creator" className="screen creator-screen" initial={{opacity:0,x:50}} animate={{opacity:1,x:0}}><div className="creator-copy"><p className="eyebrow">ORIGIN // HUMAN</p><h2>Create the one who will ascend.</h2><p className="muted">No aura. No bloodline. No destiny yet.</p><label>NAME<input value={name} maxLength={14} onChange={x=>setName(x.target.value)}/></label><Row label="HAIR" value={h} values={hair} set={setH}/><Row label="EYES" value={e} values={eyes} set={setE}/><Row label="OUTFIT" value={o} values={outfits} set={setO}/><button className="primary" disabled={busy} onClick={enter}>{busy?'CREATING...':'ENTER THE WORLD'}</button></div><div className="character-card"><div className="character-glow"/><div className="avatar-head"><div className="hair-shape"/><div className="eyes"><span/><span/></div></div><div className="avatar-body"/><div className="character-meta"><strong>{n}</strong><span>HUMAN · POWER 1</span></div></div></motion.section>}
 {screen==='world'&&c&&<motion.section key="world" className="screen world-screen" initial={{opacity:0}} animate={{opacity:1}}><div className="mountains"/><div className="mist mist-a"/><div className="mist mist-b"/><div className="world-copy"><p className="eyebrow">NINJA WORLD // OUTSKIRTS</p><h2>You feel... ordinary.</h2><p className="muted">There is nothing special about you. Yet.</p></div><div className="hud"><div><span>STATUS</span><strong>{c.rank.toUpperCase()}</strong></div><div><span>POWER</span><strong>{c.power}</strong></div></div><div className="training-panel"><span className="quest-label">CURRENT OBJECTIVE</span><h3>TRAIN YOUR BODY</h3><p>Every legend has a first rep.</p><button disabled={busy} className="train-button" onClick={train}>{busy?'SAVING...':'TRAIN'}</button>{saved&&<span className="saved">CLOUD SAVE COMPLETE</span>}</div><div className="character-silhouette"><div className="head"/><div className="torso"/></div></motion.section>}
 </AnimatePresence></main>}
function Row({label,value,values,set}:{label:string;value:string;values:string[];set:(v:string)=>void}){const i=values.indexOf(value);return <div className="option-row"><span>{label}</span><div><button onClick={()=>set(values[(i-1+values.length)%values.length])}>‹</button><strong>{value}</strong><button onClick={()=>set(values[(i+1)%values.length])}>›</button></div></div>}
