'use client';
import Link from 'next/link';
import { useRef, useState } from 'react';
import { createClient } from '@/lib/supabase/client';
type C={name:string;power:number;strength:number;speed:number;endurance:number;focus:number;rank:string;world:string};
type Intent='strike'|'heavy'|'feint'|null;
export default function SparClient({userId,character:c}:{userId:string;character:C}){
 const db=createClient();const won=c.rank.toLowerCase().includes('riven tested');
 const [enemy,setEnemy]=useState(won?0:420),[hp,setHp]=useState(170),[aura,setAura]=useState(100),[guard,setGuard]=useState(false),[intent,setIntent]=useState<Intent>(null),[locked,setLocked]=useState(false),[message,setMessage]=useState(won?'RIVEN · TEST PASSED':'Riven: “Three clean lessons. Now use them under pressure.”'),[victory,setVictory]=useState(won);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 function schedule(){setLocked(true);const pool:Exclude<Intent,null>[]=['strike','heavy','feint'];const next=pool[Math.floor(Math.random()*pool.length)];setIntent(next);setMessage(next==='strike'?'RIVEN TELEGRAPH · QUICK STRIKE':next==='heavy'?'RIVEN TELEGRAPH · HEAVY AURA HIT':'RIVEN TELEGRAPH · FEINT');timer.current=setTimeout(()=>resolve(next),900)}
 function resolve(next:Exclude<Intent,null>){let damage=next==='heavy'?38:next==='strike'?24:14;if(guard&&next!=='feint'){damage=Math.max(4,Math.round(damage*(.38-Math.min(.15,c.endurance/200))));setAura(v=>Math.max(0,v-14));setMessage('AURA GUARD · IMPACT DISPERSED')}else if(guard&&next==='feint'){setAura(v=>Math.max(0,v-18));setMessage('YOU GUARDED A FEINT · AURA WASTED')}else setMessage(next==='feint'?'RIVEN BREAKS YOUR RHYTHM':`HIT TAKEN · -${damage} HP`);setHp(v=>Math.max(0,v-damage));setGuard(false);setIntent(null);setLocked(false)}
 function hit(kind:'strike'|'burst'){if(locked||victory||hp<=0)return;if(kind==='burst'&&aura<25){setMessage('NOT ENOUGH LIFE AURA');return}const damage=kind==='burst'?36+c.strength*3:14+c.strength*2;if(kind==='burst')setAura(v=>v-25);const next=Math.max(0,enemy-damage);setEnemy(next);setMessage(kind==='burst'?`AURA BURST · ${damage} DAMAGE`:`STRIKE · ${damage} DAMAGE`);if(next<=0)void finish();else setTimeout(schedule,350)}
 function defend(){if(!locked||!intent||aura<14)return;setGuard(true);setMessage('AURA GUARD · READY')}
 function breathe(){if(locked||victory)return;setAura(v=>Math.min(100,v+28));setMessage('AURA FLOW · CONTROLLED RECOVERY');setTimeout(schedule,350)}
 async function finish(){if(timer.current)clearTimeout(timer.current);setLocked(true);if(!won){const {error}=await db.from('characters').update({power:c.power+55,strength:c.strength+3,speed:c.speed+2,endurance:c.endurance+3,focus:c.focus+2,rank:`${c.rank} · Riven Tested`,updated_at:new Date().toISOString()}).eq('user_id',userId);if(error){setMessage('SAVE FAILED · TRY AGAIN');setLocked(false);return}}setVictory(true);setMessage('RIVEN · TEST PASSED')}
 function retry(){if(timer.current)clearTimeout(timer.current);setEnemy(420);setHp(170);setAura(100);setGuard(false);setIntent(null);setLocked(false);setMessage('Riven: “Again. This time, read me.”')}
 return <main className="spar-shell"><header><span>LIFE FRONTIER // RIVEN SPARRING TEST</span><strong>{message}</strong></header>{!victory?<section className="spar-arena"><div className="spar-fighters"><div className="spar-you"><i/><b>{c.name.toUpperCase()}</b></div><div className={`spar-riven ${intent?'telegraph':''}`}><i/><b>RIVEN</b></div></div><div className="spar-hud"><div><small>YOU</small><strong>{hp} HP</strong><i><em style={{width:`${hp/1.7}%`}}/></i></div><div><small>RIVEN</small><strong>{enemy} HP</strong><i><em style={{width:`${enemy/4.2}%`}}/></i></div><div className="aura"><small>LIFE AURA</small><strong>{aura}</strong><i><em style={{width:`${aura}%`}}/></i></div></div>{hp<=0?<div className="spar-actions"><button onClick={retry}>RETRY TEST</button></div>:<div className="spar-actions"><button disabled={locked} onClick={()=>hit('strike')}>STRIKE</button><button disabled={locked||aura<25} onClick={()=>hit('burst')}>AURA BURST · 25</button><button disabled={!locked||!intent||aura<14||guard} onClick={defend}>AURA GUARD</button><button disabled={locked||aura>=100} onClick={breathe}>AURA FLOW · BREATHE</button></div>}<p className="spar-rule">Read Riven's telegraph. Guard real attacks, avoid wasting Aura on feints, and recover only when you have space.</p></section>:<section className="spar-result"><span>RIVEN'S VERDICT</span><h1>“Now you're actually fighting.”</h1><p>You maintained Life Aura under real pressure. Guard, Flow and Burst are no longer isolated drills — they form one combat loop.</p><strong>+55 POWER · +3 STRENGTH · +2 SPEED · +3 ENDURANCE · +2 FOCUS</strong><blockquote>“You're ready to leave my camp. But something in the western valley is swallowing every Aura signature that enters it.”</blockquote><p className="danger">NEW AREA DETECTED · SILENT VALLEY</p><button disabled>SILENT VALLEY · NEXT MILESTONE</button><Link href="/life-frontier">RETURN TO FRONTIER →</Link></section>}</main>}
