'use client';
import Link from 'next/link';import {motion} from 'framer-motion';import {useRef,useState} from 'react';import {createClient} from '@/lib/supabase/client';
type C={name:string;power:number;strength:number;speed:number;endurance:number;focus:number;rank:string};
export default function NightSignalClient({userId,initialCharacter}:{userId:string;initialCharacter:C}){const db=createClient();const [c,setC]=useState(initialCharacter),[phase,setPhase]=useState<'brief'|'fight'|'win'>('brief'),[hp,setHp]=useState(100),[enemy,setEnemy]=useState(180),[chakra,setChakra]=useState(100),[incoming,setIncoming]=useState(false),[locked,setLocked]=useState(false),[text,setText]=useState('The signal appears only after sunset.'),[counter,setCounter]=useState(false);const attackAt=useRef(0),timer=useRef<ReturnType<typeof setTimeout>|null>(null);
function start(){setPhase('fight');setHp(100);setEnemy(180);setChakra(100);setText('ANOMALY CONTACT · It does not move like a human.');setLocked(false)}
function enemyTurn(){setLocked(false);setIncoming(true);attackAt.current=Date.now();setText('CHAKRA SPIKE INCOMING · REACT');timer.current=setTimeout(()=>resolve(false),950)}
function hit(dmg:number,label:string,cost=0){if(locked||incoming||chakra<cost)return;setLocked(true);if(cost)setChakra(v=>v-cost);const n=Math.max(0,enemy-dmg);setEnemy(n);setText(`${label} · ${dmg} DAMAGE`);if(n<=0){void finish();return}setTimeout(enemyTurn,500)}
function resolve(evaded:boolean){if(!incoming&&!evaded)return;if(timer.current)clearTimeout(timer.current);setIncoming(false);setLocked(true);if(evaded){setCounter(true);setText('FLASH STEP EVADE · COUNTER WINDOW');setChakra(v=>Math.max(0,v-20));setTimeout(()=>{setCounter(false);setLocked(false)},700);return}const dmg=Math.max(12,27-Math.floor(c.endurance/2));setHp(v=>Math.max(0,v-dmg));setText(`ANOMALY HIT · ${dmg} DAMAGE`);setTimeout(()=>setLocked(false),550)}
function flashStep(){if(!incoming||chakra<20)return;const t=Date.now()-attackAt.current;if(t>=350&&t<=820)resolve(true);else{setText('FLASH STEP MIS-TIMED');resolve(false)}}
async function finish(){setLocked(true);setText('ANOMALY DISPERSED · THE SIGNAL LEAVES A RESIDUE');const {data}=await db.from('characters').update({rank:'Chakra Vanguard · Flash Step',power:c.power+20,focus:c.focus+2,updated_at:new Date().toISOString()}).eq('user_id',userId).select('name,power,strength,speed,endurance,focus,rank').single();if(data)setC(data as C);setTimeout(()=>setPhase('win'),900)}
return <main className={`night-shell ${counter?'countering':''}`}><div className="moon"/><div className="night-trees"/><header><span>C-RANK // NIGHT SIGNAL</span><strong>{text}</strong></header>{phase==='brief'&&<section className="night-card"><span>MISSION 003</span><h1>Find what is calling.</h1><p>An unknown chakra signature is pulsing beyond the northern treeline. Kairo cannot identify it. You are ordered to observe — not engage.</p><button onClick={start}>ENTER THE DARK</button><Link href="/village">RETURN</Link></section>}{phase==='fight'&&<><div className="night-hud"><div><b>{c.name}</b><i><em style={{width:`${hp}%`}}/></i><small>{hp} HP</small></div><div><b>UNKNOWN ANOMALY</b><i><em style={{width:`${enemy/180*100}%`}}/></i><small>{enemy} HP</small></div></div><div className="night-chakra">CHAKRA {chakra}/100 <i><em style={{width:`${chakra}%`}}/></i></div><motion.div className="night-fighter hero" animate={counter?{x:[0,180,145]}:{}}><div/><span/></motion.div><motion.div className={`night-fighter anomaly ${incoming?'attacking':''}`} animate={incoming?{x:[0,-70,0]}:{}}><div/><span/></motion.div>{incoming&&<motion.div className="danger-ring" initial={{scale:.3,opacity:1}} animate={{scale:2.6,opacity:0}} transition={{duration:.95}}/>}<nav>{hp<=0?<button onClick={start}>RETRY</button>:<><button disabled={locked||incoming} onClick={()=>hit(Math.max(12,9+c.strength*2),'STRIKE')}>STRIKE</button><button disabled={locked||incoming||chakra<30} onClick={()=>hit(26+c.focus*3,'CHAKRA BURST',30)}>CHAKRA BURST · 30</button><button className={incoming?'flash-ready':''} disabled={!incoming||chakra<20} onClick={flashStep}>FLASH STEP · EVADE 20</button>{counter&&<button className="counter-btn" onClick={()=>hit(42+c.speed*2,'FLASH COUNTER')}>COUNTER</button>}</>}</nav></>}{phase==='win'&&<section className="night-card victory"><span>C-RANK COMPLETE</span><h1>CHAKRA VANGUARD</h1><p>The anomaly was not human. Worse: its chakra signature does not belong to this region. Kairo wants the residue examined immediately.</p><div>+20 POWER · +2 FOCUS</div><Link href="/village">REPORT TO KAIRO</Link></section>}</main>}
